[project]
name = "smlp"
version = "0.1.0"
description = "symbolic machine learning prover"
readme = "README.md"
requires-python = "==3.11.12"
dependencies = [
    "doepy>=0.0.1",
    "gmp>=0.0.17",
    "icecream>=2.1.8",
    "jenkspy>=0.4.1",
    "keras<3",
    "keras-tuner>=1.4.7",
    "loguru>=0.7.3",
    "meson>=1.9.1",
    "mrmr-selection>=0.2.8",
    "numpy>=1.26.4",
    "pandas>=2.1.4",
    "pkgconfig>=1.5.5",
    "pre-commit>=4.3.0",
    "pycaret>=3.3.2",
    "pydoe>=0.3.8",
    "pysubgroup>=0.8.0",
    "ruff>=0.14.1",
    "scikit-learn>=1.4.2",
    "seaborn>=0.13.2",
    "setuptools>=80.9.0",
    "tensorflow>=2.13<2.16",
    "wheel>=0.45.1",
]
